name: Build Firmware and create OTA Update

# TBD change trigger from manual to push or other suitable
on: workflow_dispatch

# on:
#   push:
#     branches: ["main"]

jobs:
  iot_connect:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # - name: Build Firmware TBD
      #   working-directory: ./tbd
      #   run: TBD

      - name: Install dependencies
        working-directory: ./iot-connect
        run: pip install -r requirements.txt

      - name: Create OTA update
        working-directory: ./iot-connect
        env:
          USERNAME: ${{ secrets.IOT_CONNECT_USERNAME }}
          PASSWORD: ${{ secrets.IOT_CONNECT_PASSWORD }}
          SOLUTION_KEY: ${{ secrets.IOT_CONNECT_SOLUTION_KEY }}
        run: echo "TBD"
