name: Build Firmware and create OTA Update

# TBD change trigger from manual to push or other suitable
on: workflow_dispatch

# on:
#   push:
#     branches: ["main"]

jobs:
  fw_build:
    runs-on: codebuild-AvnetStm32FWBuild-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup tools
        run: ./scripts/setup-project.sh

      - name: Build Firmware
        run: |
          /opt/st/stm32cubeide_1.12.1/headless-build.sh -data . -import ./stm32/Projects/b_u585i_iot02a_ntz -build b_u585i_iot02a_ntz
          ls ./stm32/Projects/b_u585i_iot02a_ntz/Debug/

      # - name: Setup python environment
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.12'

      # - name: Install dependencies
      #   working-directory: ./iot-connect
      #   run: pip install -r requirements.txt

      # - name: Create OTA update
      #   working-directory: ./iot-connect
      #   env:
      #     USERNAME: ${{ secrets.IOT_CONNECT_USERNAME }}
      #     PASSWORD: ${{ secrets.IOT_CONNECT_PASSWORD }}
      #     SOLUTION_KEY: ${{ secrets.IOT_CONNECT_SOLUTION_KEY }}
      #   run: echo "TBD"
