name: Solution Deploy

on: workflow_dispatch

jobs:
  iot_connect:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./iot-connect
        run: pip install -r requirements.txt

      - name: Setup IoTConnect
        working-directory: ./iot-connect
        env:
          USERNAME: ${{ secrets.IOT_CONNECT_USERNAME }}
          PASSWORD: ${{ secrets.IOT_CONNECT_PASSWORD }}
          SOLUTION_KEY: ${{ secrets.IOT_CONNECT_SOLUTION_KEY }}
          ENTITY_NAME: ${{ secrets.IOT_CONNECT_ENTITY_NAME }}
          CERTIFICATE: ${{ secrets.IOT_CONNECT_CERTIFICATE }}
        run: python ./iot_connect_setup.py "$USERNAME" "$PASSWORD" "$SOLUTION_KEY" "$ENTITY_NAME" "$CERTIFICATE"

  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: './demo-cdk/package-lock.json'

      - name: Install dependencies
        working-directory: ./demo-cdk
        run: npm install

      - name: Install AWS CDK
        working-directory: ./demo-cdk
        run: npm i -g aws-cdk

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Prepare Lambda layer
        run: |
          mkdir -p "iot-connect-layer"
          cp -R "iot-connect" "iot-connect-layer/python"
          ls -la "iot-connect-layer/python"

      - name: Synth stack
        working-directory: ./demo-cdk
        env:
          ST_USERNAME: ${{ secrets.STDEVCLOUD_USERNAME }}
          ST_PASSWORD: ${{ secrets.STDEVCLOUD_PASSWORD }}
          IOTCON_USERNAME: ${{ secrets.IOT_CONNECT_USERNAME }}
          IOTCON_PASSWORD: ${{ secrets.IOT_CONNECT_PASSWORD }}
          IOTCON_SOLUTION_KEY: ${{ secrets.IOT_CONNECT_SOLUTION_KEY }}
          IOTCON_ENTITY_NAME: ${{ secrets.IOT_CONNECT_ENTITY_NAME }}
          GIT_ARN: ${{ secrets.GIT_ARN }}
        run: cdk synth --context stUsername="$ST_USERNAME" --context stPassword="$ST_PASSWORD" --context iotConnectUsername="$IOTCON_USERNAME" --context iotConnectPassword="$IOTCON_PASSWORD" --context iotConnectSolutionKey="$IOTCON_SOLUTION_KEY" --context iotConnectEntity="$IOTCON_ENTITY_NAME" --context gitOwner="$GITHUB_REPOSITORY_OWNER" --context gitRepo="${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" --context gitArn="$GIT_ARN"

      - name: Deploy stack
        working-directory: ./demo-cdk
        env:
          ST_USERNAME: ${{ secrets.STDEVCLOUD_USERNAME }}
          ST_PASSWORD: ${{ secrets.STDEVCLOUD_PASSWORD }}
          IOTCON_USERNAME: ${{ secrets.IOT_CONNECT_USERNAME }}
          IOTCON_PASSWORD: ${{ secrets.IOT_CONNECT_PASSWORD }}
          IOTCON_SOLUTION_KEY: ${{ secrets.IOT_CONNECT_SOLUTION_KEY }}
          IOTCON_ENTITY_NAME: ${{ secrets.IOT_CONNECT_ENTITY_NAME }}
          GIT_ARN: ${{ secrets.GIT_ARN }}
        run: cdk deploy --all --require-approval never --context stUsername="$ST_USERNAME" --context stPassword="$ST_PASSWORD" --context iotConnectUsername="$IOTCON_USERNAME" --context iotConnectPassword="$IOTCON_PASSWORD" --context iotConnectSolutionKey="$IOTCON_SOLUTION_KEY" --context iotConnectEntity="$IOTCON_ENTITY_NAME" --context gitOwner="$GITHUB_REPOSITORY_OWNER" --context gitRepo="${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" --context gitArn="$GIT_ARN"
